### ISSUE TITLE
Support for version 4.0

### ISSUE THREAD

**Issue by pgrm** [autofac/Autofac.Extras.DynamicProxy#1]
Hi, what are the plans on releasing version 4.0 of DynamicProxy, which would work with Autofac 4.0?

**Comment by tillig** [comment]
We will eventually release the full stack compatible with 4.0, but we need to get the core bits solidified first. We are running into some challenges with automated builds and PCL targeting and need to nail those down before we push things down through the rest of the stack. We are working as hard as we can but there is not a specific date committed at this point.
