### ISSUE TITLE
Autofac.Extras.DynamicProxy2 not available for .NETCoreApp,Version=v1.0

### ISSUE THREAD

**Issue by toanxyz** [autofac/Autofac.Extras.DynamicProxy#10]
Autofac.Extras.DynamicProxy2 not available for .NETCoreApp,Version=v1.0 when adding via Nuget package.
Please help me because i wanna implement Interceptor concept.

.NET Core is realeased RC2!

**Comment by tillig** [comment]
Unfortunately, Castle.Core has not been updated quite yet to support netstandard so we can't bring this functionality forward.

However, it appears [they are now working on supporting netstandard 1.3](https://github.com/castleproject/Core/blob/netcore/buildscripts/Castle.Core.nuspec) which would open up the platform support for this library. When that's available, we will update to Castle.Core 4.0.0 and support netstandard.

**Comment by tillig** [comment]
Oops, looks like this is a duplicate for #8 - I'm going to close this as duplicate and update things over there as needed.
