### ISSUE TITLE
Support for .NET 4.5 in Nuget

### ISSUE THREAD

**Issue by jarjarbrinksmanship** [autofac/Autofac.Extras.DynamicProxy#12]
It looks like there isn't a build for .NET 4.5 published to Nuget (only 4.5.1).

Nuget error message: 

install-package : Could not install package 'Autofac.Extras.DynamicProxy 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by alexmg** [comment]
I have pushed 4.0.1 of Autofac.Extras.DynamicProxy to NuGet.
