### ISSUE TITLE
Update Castle.Core nuspec references

### ISSUE THREAD

**Issue by mwpowellhtx** [autofac/Autofac.Extras.DynamicProxy#15]
Dependency on _Castle.Core_ `3.2.2` is too strict, suggest at least a sensible interval notation, say through `[3.2.2,4.0.0)`; _Castle.Core_ is released at `3.3.3` now. I don't know how that potentially breaks this.

**Comment by tillig** [comment]
Are you having a difficult time adding a later Castle.Core reference? The way NuGet interprets a single listed version is `>= version` - in this case, `>=3.2.2`. You can verify it by [looking at the listing on the NuGet page](http://www.nuget.org/packages/Autofac.Extras.DynamicProxy/).

**Comment by mwpowellhtx** [comment]
Thanks, I'll check that out.

**Comment by mwpowellhtx** [comment]
Updated in my clone of the repository to latest _Castle.Core_, and the tests are working. Will leave it at that. Thanks again!
