### ISSUE TITLE
Should document Visual Studio and C# language dependencies

### ISSUE THREAD

**Issue by mwpowellhtx** [autofac/Autofac.Extras.DynamicProxy#16]
You should probably document the _C# language_ dependencies, i.e. `nameof` operator, for starters; implied also _Visual Studio_ along with that. Background, I've been happily tooling along on _VS2013_. While I did spend a little time getting acquainted with _VS2015_ around about the CTP, I haven't made the leap yet, much less _C# 6.0_. I probably should, but just haven't made it a priority yet.

**Comment by tillig** [comment]
You should only need this information if you're compiling from source. If you're doing that, we [already have all that listed in the contributor's guide](https://github.com/autofac/Autofac/blob/master/CONTRIBUTING.md) which is cross-linked [from the documentation](http://autofac.readthedocs.io/en/latest/contributors.html).
