### ISSUE TITLE
How to register target instance with interceptors

### ISSUE THREAD

**Issue by mwpowellhtx** [autofac/Autofac.Extras.DynamicProxy#17]
Hello,

Okay, so I register my _IInterceptor_ with the container builder. However, _InterceptedBy_ does not want provide any sort of context, nor does it seem to want any types in terms of _IInterceptor_.

Further, _InterceptedBy_ seems to want _Services_, _Types_, or _names_; not sure how that aligns to my _IInterceptor_. Or perhaps I've got the wrong extension method in mind here...

Thanks...

**Comment by tillig** [comment]
[Have you read the docs?](http://autofac.readthedocs.io/en/latest/advanced/interceptors.html)

Also, usage questions ("How do I...?") are great candidates for StackOverflow rather than issues. We monitor both spots, but you have a lot more people who can get you help faster on SO.

**Comment by mwpowellhtx** [comment]
Thanks for the feedback. I reviewed the docs you provided, as far as I know I am registering with Autofac in the expected manner. However, the instrumentation dots do not seem to be connecting properly.

FWIW, I posted on [SO](http://stackoverflow.com/questions/40063883/using-perfit-with-autofac-extras-dynamicproxy-i-e-castle-core-not-working).

Or if there's a better performance monitoring instrumentation choice, I'm open to that as well.

Thanks!

**Comment by mwpowellhtx** [comment]
Been chewing on this, and it just doesn't make sense to me. What's the point of identifying an interceptor for whichever classes need to be instrumented if I've still got to "install" a Perf runtime? It just seems to me that something isn't being initialize quite right, but either DynamicProxy and/or PerfIt; which is the blurred distinction for me at the moment. Just looking for some clarity.

**Comment by tillig** [comment]
Any follow up here will be on SO. If you have additional things you have tried that will help answer the question, update the question on SO. That will help everyone looking at the question understand what you've tried and what's not working.
