### ISSUE TITLE
Visual Studio 2017 Castle Core depends on System.ComponentModel.TypeConverter but was not found

### ISSUE THREAD

**Issue by moliveto** [autofac/Autofac.Extras.DynamicProxy#19]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1603	Castle.Core 4.0.0 depends on System.ComponentModel.TypeConverter (>= 4.0.1) but System.ComponentModel.TypeConverter 4.0.1 was not found. An approximate best match of System.ComponentModel.TypeConverter 4.1.0 was resolved.	Provider	D:\VS 2017\Interception\Provider\Provider.csproj	1

**Comment by moliveto** [comment]
see
https://github.com/moq/moq4/issues/375

**Comment by tillig** [comment]
You should file this with [castle project](https://github.com/castleproject/Core). We rely on that, but we don't have control of it.

On a side note, I've found a lot of these sorts of things popping up for a lot of my work and personal projects, like Microsoft went through and delisted a bunch of things from NuGet when they released .NET Core 2.0. I've been filling issues with them about it. You should, too.

**Comment by hikalkan** [comment]
I believe you should upgrade to Castle.Core 4.1+ to resolve this issue because Castle.Core 4.1 depends on TypeConverter 4.3.0.

**Comment by tillig** [comment]
This has caused enough confusion that we went ahead and did that update. A.E.DP 4.3.0 released.
