### ISSUE TITLE
fix castle.core warn

### ISSUE THREAD

**Issue by Varorbc** [autofac/Autofac.Extras.DynamicProxy#21]
warn info:

Castle.Core 4.0.0 依赖于 System.ComponentModel.TypeConverter (>= 4.0.1)，但找不到 System.ComponentModel.TypeConverter 4.0.1。 已解决 System.ComponentModel.TypeConverter 4.1.0 的近似最佳匹配

**Comment by tillig** [comment]
Duplicate of #19
