### ISSUE TITLE
Why isn't DynamicProxy referencing newer Versions of AutoFac

### ISSUE THREAD

**Issue by marcBalta** [autofac/Autofac.Extras.DynamicProxy#26]
My Problem is that Autofac up to 4.0.1 has a severe bug which is https://github.com/autofac/Autofac/issues/789 . But unfortunatley this bug is fixed only in the following versions which are not supported by DynamicProxy so I'm stuck with Autofac 4.0.1 and this bug if I want to use DynmicProxy.

So is there any reason why Dynamic Proxy is still referencing the old Version of AutoFac?

**Comment by tillig** [comment]
[This is one of our FAQs.](http://autofac.readthedocs.io/en/latest/faq/binding-redirect.html)

**Comment by tillig** [comment]
(You can absolutely update your local reference of Autofac to something new. There's no change in A.E.DP required.)

**Comment by marcBalta** [comment]
Ok, thank you very much.  Didn't know about bindingRedirects.
