### ISSUE TITLE
Autofac.Extras.DynamicProxy2 v3.0.6 got a exception

### ISSUE THREAD

**Issue by supershowwei** [autofac/Autofac.Extras.DynamicProxy#3]
I report in http://stackoverflow.com/questions/31174406/autofac-extras-dynamicproxy2-v3-0-6-got-a-exception.

**Comment by alexmg** [comment]
This issue should now be resolved. There is a 3.0.7 package available on NuGet. Please let us know if you are still having any problems.

**Comment by supershowwei** [comment]
Thanks. The problem fixed.
