### ISSUE TITLE
The EnableClassInterceptors method is not supported.

### ISSUE THREAD

**Issue by tinylit** [autofac/Autofac.Extras.DynamicProxy#30]
Test environment: in Autofac. Extras. DynamicProxy. Test. AttributedInterfaceInterceptionFixture, Test to fail.
A:
 [Fact]
public void FindsInterceptionAttributeOnReflectionComponentWithClass()
{
	var builder = new ContainerBuilder();
	builder.RegisterType&lt;C&gt;().EnableClassInterceptors().InterceptedBy(typeof(AddOneInterceptor));
	builder.RegisterType&lt;AddOneInterceptor&gt;();
	var cpt = builder.Build().Resolve&lt;C&gt;();
	Assert.Equal(11, cpt.GetI());
}
B:
 [Fact]
public void FindsInterceptionAttributeOnReflectionComponentWithClass2()
{
	var builder = new ContainerBuilder();
	builder.RegisterType&lt;C2&gt;().EnableClassInterceptors();
	builder.RegisterType&lt;AddOneInterceptor&gt;();
	var cpt = builder.Build().Resolve&lt;C2&gt;();
	Assert.Equal(11, cpt.GetI()); 
}
[Intercept(typeof(AddOneInterceptor))]
public class C2 : IHasI
{
	public C2()
	{
		I = 10;
	}

	public int I { get; private set; }

	public int GetI()
	{
		return I;
	}
}

**Comment by gao87926** [comment]
Which version of autofac you are using?

**Comment by tillig** [comment]
We haven't heard any feedback here so I'm closing this issue.
