### ISSUE TITLE
AutoFac 5.0 not supported

### ISSUE THREAD

**Issue by connellsharp** [autofac/Autofac.Extras.DynamicProxy#31]
Now that Aufofac 5.0 has been released, the integration with Autofac.Extras.DynamicProxy throws an exception.

Here is [a test repo demonstrating the error](https://github.com/connellw/Autofac5DynamicProxyIssue/blob/master/Program.cs).

It looks to be because of [this commit](https://github.com/autofac/Autofac/commit/5a74ca80c30462166abbfb1aa23b44bdb30cd0cf#diff-945c28836f31d645dc9d4ee202895f68) and that `ComponentRegistration.RaiseActivating` is now being called twice. This causes an error when calling the second `ProxyGenerator.CreateInterfaceProxyWithTarget`:

> Castle.DynamicProxy.ProxyGenerationException: This is a DynamicProxy2 error: Target type for the proxy implements Castle.DynamicProxy.IProxyTargetAccessor which is a DynamicProxy infrastructure interface and you should never implement it yourself. Are you trying to proxy an existing proxy?

**Comment by tillig** [comment]
Yup, that's mentioned [in the release notes](https://github.com/autofac/Autofac/releases/tag/v5.0.0)

> ## Still TODO
> Now that Autofac 5.0 is out, there is still a lot to do. We'll be working on these things as fast as we can:
>
> - Updating integration packages we support so they ensure compatibility with Autofac 5.
> - Updating the documentation to reflect the above changes.
>
> Some of this is sitting in branches ready to go, other things need to be done now that we have this core package out there.
>
> **If your favorite integration isn't ready yet, we're doing our best.** Rather than filing "When will this be ready?" issues, consider pull requests with the required updates.

**Comment by forever84721** [comment]
Autofac 5.0.0
Autofac.Extras.DynamicProxy 4.5.0
Not workig
----
Autofac 6.0.0
Autofac.Extras.DynamicProxy 6.0.0
Working
----
If I have to use Autofac 5.0.0,
How can I solve this problem?
I can't find a related discussion, thank you.

**Comment by tillig** [comment]
This is a different issue, but: you can't. Any time you see a major version upgrade (Autofac.Extras.DynamicProxy v5.0.0 to v6.0.0) it indicates a breaking change. In this case, the breaking change is the forced upgrade to Autofac core. It's always wise to read the release notes before taking any update. [In this case, the release notes tell you about the forced upgrade.](https://github.com/autofac/Autofac.Extras.DynamicProxy/releases/tag/v6.0.0) If you can't upgrade core Autofac, you can't take this upgrade either.
