### ISSUE TITLE
Autofac.Extensions.DependencyInjection 6.0 version cannot be used aop

### ISSUE THREAD

**Issue by anjoy8** [autofac/Autofac.Extras.DynamicProxy#33]
hello,
If it's 5.0, there's no problem,
But if I upgrade to Autofac.Extensions.DependencyInjection 6.0,
```
<ItemGroup>
PackageReference Include" "Autofac.Extensions.DependencyInjection""Version" "6.0.0" /
PackageReference Include" "Autofac.Extras.DynamicsProxy" Version" "4.5.0" /
</ItemGroup>
```

will be reported error:
```
An unhandled antalysed dysd while processing the request.
ProxyGenerationException: This is a DynamicSProxy2 error: Target type for the proxy implements Castle.Dynamics.IProxyAccessorTarget is a Dynamics infrastructure interface and you want never it. Are Are you trying to proxy an exist proxying?
```

There's a question here:
[Unable to hook up interceptor on classes/interfaces in asp.net core 3.1 application](https://stackoverflow.com/questions/60067943/unable-to-hook-up-interceptor-on-classes-interfaces-in-asp-net-core-3-1-applicat)

**Comment by tillig** [comment]
DynamicProxy hasn't been updated for 5.0 yet.

**Comment by anjoy8** [comment]
OKay,thx
