### ISSUE TITLE
Constructor on type 'xxxProxy' not found

### ISSUE THREAD

**Issue by 835718973** [autofac/Autofac.Extras.DynamicProxy#43]
When I use Autofac.Extras.DynamicProxy in my wpf project,some aop can't not work with Constructor on type 'xxxProxy' not found.
![image](https://user-images.githubusercontent.com/20808204/122517668-e696e600-d042-11eb-97c5-83008431f980.png)
it appears on the wpf progrem has startup.if i resolve the service when I just build the autofaccontainer,it can also works right.so it does very curious。

![image](https://user-images.githubusercontent.com/20808204/122518349-a97f2380-d043-11eb-8a73-56afbcd384b2.png)

**Comment by tillig** [comment]
Can you provide a simple reproduction so we can see it happen? By simple, I mean ideally a small unit test - no assembly loading, no building lists of registrations in interesting and custom ways, etc. The absolute least amount of code to make the issue occur.

**Comment by tillig** [comment]
Given there's no reproduction here, I'm going to close this issue. If there is something we can do to help, let us know.
