### ISSUE TITLE
Security vulnerability due to Castle.Core 4.4.0 dependency

### ISSUE THREAD

**Issue by sstassen-wowcorp** [autofac/Autofac.Extras.DynamicProxy#51]
Dependency on Castle.Core 4.4.0 takes out a dependency on NETStandard.Library 1.6.1, which in turn depends on System.Text.RegularExpressions 4.3.0, which has a security vulnerability. See https://github.com/dotnet/announcements/issues/111

**Comment by olfonur** [comment]
Castle.Core version looks upgraded in [the latest version](https://github.com/autofac/Autofac.Extras.DynamicProxy/compare/v6.0.1...develop#diff-e1ad1b93cce3c1c5afff872ab809a35930061adbd1dd6ccc959e1dffa1e36da6). But in the latest version of package System.Text.RegularExpressions 4.3.0

**Comment by tillig** [comment]
Oh, yup, looks like we forgot to release. Let me get on that.

**Comment by tillig** [comment]
I [submitted a PR](https://github.com/autofac/Autofac.Extras.DynamicProxy/pull/54) to update the build a little and add a `net6` target before we release so we're closer to the new Castle.Core target-wise. We'll release right after that.

**Comment by olfonur** [comment]
Unfortunately PR merge failed.Would you check please?

**Comment by tillig** [comment]
Please be patient. The build failed, but even if it had passed it hadn't been reviewed. We'll get there.

**Comment by olfonur** [comment]
We have a security vulnerability in one of our projects. The due date given to us is about to pass, so I'm hurrying :)

**Comment by tillig** [comment]
You are free to grab a pre-release from MyGet and get past that. I respect you have deadlines, but at the same time, you're getting free software from 100% unpaid volunteers doing this all in their spare time instead of spending time with families or doing other hobbies.

`https://www.myget.org/F/autofac/api/v3/index.json` is the feed location.

**Comment by olfonur** [comment]
You are doing a very valuable job. I respect. Thanks again 🙏

**Comment by tillig** [comment]
Sorry for the delay, v7.0.0 is out.
