### ISSUE TITLE
Add support for netstandard 1.3 when Castle.Core 4.0.0 is released

### ISSUE THREAD

**Issue by igatanasov** [autofac/Autofac.Extras.DynamicProxy#8]
Hi,

Castle.Core just released .net core/standard support - https://www.nuget.org/packages/Castle.Core/4.0.0-alpha001. Do you plan to update the nuget packages for  Autofac.Extras.DynamicProxy?

**Comment by tillig** [comment]
Oh, nice, thanks for pointing this out!

It's definitely something we'd like to do, but we probably won't start on it until after RC2 is out with dotnet CLI. We've already got a lot of struggle trying to get RC2 support running with core Autofac - no sense in adding extra churn downstream.

**Comment by igatanasov** [comment]
Hi @tillig ,

since dotnet CLI is released and Castle.Core support .net code 1.0 do you need any help to proceed with .net core support?

**Comment by alexmg** [comment]
I think the majority of the work will be getting the build running on CLI. One of the nice things about splitting out all the repositories was simplification of the build; we just have to drop in a `appveyor.yml` file into these smaller solutions and AppVeyor takes care of the rest.

I would prefer that we migrate these smaller packages to CLI once AppVeyor has proper support for CLI builds and we have that same experience. On the main Autofac project we have had to turn off all the automatic goodness and manually run all the build steps from a PS script. I've done a little digging around and it's not clear to me exactly where things stand on this front, but I suspect if things are going to be more stable now with CLI that proper support for it won't be too far off.

When the CLI support is available we would certainly be happy to receive your help migrating this pacakge over. :smiley:

**Comment by igatanasov** [comment]
Hi @alexmg ,

Thanks for your detailed explanation. I will be glad to help you with this migration.

**Comment by tillig** [comment]
It appears [Castle.Core is still working on supporting netstandard 1.3](https://github.com/castleproject/Core/blob/netcore/buildscripts/Castle.Core.nuspec) which would open up the platform support here. When that's available, we can update to Castle.Core 4.0.0 and support netstandard.

Until then, we'll need to issue an update for compatibility with Autofac 4.0.0 support (which will most likely make this a 4.0.0 release) and then issue a subsequent release for the updated platform support.

**Comment by igatanasov** [comment]
Hi @tillig 

Actually I will try to help Castle.Core members with the upgrade so we can proceed forward.

Once again thanks for your update on this!

**Comment by gdereese** [comment]
@tillig, any updates on this?  I am trying to migrate my project to .NET Core 1.0 RTM but am blocked from completing it due to this issue.

**Comment by tillig** [comment]
Nope. It appears that [they released Castle.Core 4.0.0-beta001](https://www.nuget.org/packages/Castle.Core/4.0.0-beta001) just a few days ago, but I'll be honest, [we're pretty swamped trying to get everything updated](http://www.paraesthesia.com/archive/2016/06/29/netcore-rtm-where-is-autofac/) so don't expect instant results. If you want to submit a PR and help us out, it can potentially speed things up, otherwise, sorry, you'll just have to be patient.

**Comment by gdereese** [comment]
I submitted pull request #11 to this repo that hopefully addresses the issue.  All unit tests passed after upgrading the Castle.Core dependency to 4.0.0-beta001, so I updated the nuspec to reference that updated package.  I'm naively hoping it's that simple.  If not, feedback/direction is welcome.

**Comment by gdereese** [comment]
#11

**Comment by tillig** [comment]
We can't release a stable package on a prerelease of Castle.Core so even if we updated to that version, we're still sort of stuck.

We'll also need to update our projects here to target netstandard 1.3 once that's done, which isn't hard but isn't two minutes, either.

Anyway, still on hold, basically, until Castle releases a stable netstandard targeted package.

**Comment by tillig** [comment]
As of Oct 24, 2016 it appears Castle.Core has still not released a stable netstandard package. We'll keep periodically checking back.

**Comment by tillig** [comment]
For those checking in - the ability to support a `netstandard` target is also what would allow us to support an application based on `NETCoreApp` - that's all .NET Core / `netstandard` stuff.

On Oct 27, 2016 [Castle.Core released 4.0.0-beta002](https://www.nuget.org/packages/Castle.Core/4.0.0-beta002) but we are, again, still stuck until they have a _stable release_ (i.e., not beta).

**Comment by d-saravanan** [comment]
I would also like to hold my code upgrade for the castle team, in case of any further updates, please do notify me too.

**Comment by emmekappa** [comment]
Castle.Core 4.0 is out.

https://www.nuget.org/packages/Castle.Core/4.0.0

**Comment by tillig** [comment]
Excellent. We can start work on this as possible, then.

**Comment by tillig** [comment]
Just pushed [v4.2.0](https://www.nuget.org/packages/Autofac.Extras.DynamicProxy/4.2.0) with netstandard 1.3 support.
